<?php

/**
* Implements hook_block_info().
*/
function crf_main_block_info() {
  $blocks = array();
  $blocks['crf_main'] = array(
    'info' => t('Crowdfun - Main menu'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['crf_add_campaign'] = array(
    'info' => t('Crowdfun - Add Campaign'),
  );
  return $blocks;
}


/**
* Implements hook_block_view().
*/
function crf_main_block_view($delta) {
	// Add module JS to head
	drupal_add_js(drupal_get_path('module', 'crf_main') . '/js/crf_main.js', array('scope' => 'header'));

	$block = array();

  switch ($delta) {
    case 'crf_main':

    	// Load the main menu
    	$menu = menu_tree('main-menu');

    	$options = array(
    		'attributes' => array(
    			'id' => 'main-menu',
    			'class' => 'main-menu__icon',
    		)
    	);
    	$output = l(t('menu'), '', $options);
    	$output .= drupal_render($menu);

      $block['content'] = $output;

      break;
      case 'crf_add_campaign':
      	$options = array(
	    		'attributes' => array(
	    			'id' => 'add-campaign',
	    			'class' => 'add-campaign__icon',
	    		)
	    	);
	    	$output = l(t('add campaign'), '/node/add/campaign', $options);

	      $block['content'] = $output;
      break;
  }

  return $block;
}
